# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-01-02 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixerrapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='title',
            field=models.CharField(max_length=501),
        ),
    ]
