# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-12-31 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sixerrapp', '0002_gig'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gig',
            old_name='catgory',
            new_name='category',
        ),
    ]
