# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-01-03 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixerrapp', '0003_auto_20190102_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='company',
        ),
        migrations.AddField(
            model_name='gig',
            name='company',
            field=models.ManyToManyField(to='sixerrapp.Company'),
        ),
    ]
