# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-01-06 04:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sixerrapp', '0004_auto_20190103_0348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='about',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='slogan',
        ),
    ]
