# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-01-02 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixerrapp', '0006_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='category',
            field=models.CharField(choices=[('GD', 'Art & Design'), ('BFA', 'Business, Finance & Accounting'), ('MS', 'Math & Science'), ('ED', 'Education'), ('IT', 'Information Technology')], max_length=2),
        ),
    ]
