# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-07-01 18:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sixerrapp', '0007_auto_20190227_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sixerrapp.Hashtag')),
                ('hashtags', models.ManyToManyField(related_name='related_industry_hashtags', to='sixerrapp.Hashtag')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('requirement', models.TextField()),
                ('url', models.TextField()),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(null=True, upload_to='resumes')),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sixerrapp.Hashtag')),
                ('hashtags', models.ManyToManyField(related_name='related_sector_hashtags', to='sixerrapp.Hashtag')),
            ],
        ),
        migrations.CreateModel(
            name='SkillOrTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sixerrapp.Hashtag')),
                ('hashtags', models.ManyToManyField(related_name='related_skill_or_tool_hashtags', to='sixerrapp.Hashtag')),
                ('industries', models.ManyToManyField(to='sixerrapp.Industry')),
                ('sectors', models.ManyToManyField(to='sixerrapp.Sector')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('photo', models.FileField(upload_to='stories')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='gig',
            name='company',
        ),
        migrations.RemoveField(
            model_name='gig',
            name='user',
        ),
        migrations.RemoveField(
            model_name='company',
            name='description',
        ),
        migrations.RemoveField(
            model_name='company',
            name='time',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='resume',
        ),
        migrations.AddField(
            model_name='company',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sixerrapp.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Gig',
        ),
        migrations.AddField(
            model_name='story',
            name='companies',
            field=models.ManyToManyField(to='sixerrapp.Company'),
        ),
        migrations.AddField(
            model_name='story',
            name='hashtags',
            field=models.ManyToManyField(to='sixerrapp.Hashtag'),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sixerrapp.Company'),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='personal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sixerrapp.Personal'),
        ),
        migrations.AddField(
            model_name='personal',
            name='companies',
            field=models.ManyToManyField(to='sixerrapp.Company'),
        ),
        migrations.AddField(
            model_name='personal',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sixerrapp.Profile'),
        ),
        migrations.AddField(
            model_name='job',
            name='companies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sixerrapp.Company'),
        ),
        migrations.AddField(
            model_name='job',
            name='hashtags',
            field=models.ManyToManyField(to='sixerrapp.Hashtag'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hashtags',
            field=models.ManyToManyField(to='sixerrapp.Hashtag'),
        ),
    ]
