# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-01-02 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixerrapp', '0007_auto_20190102_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='description',
            field=models.TextField(),
        ),
    ]
