# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-07-03 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixerrapp', '0008_auto_20190701_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='hashtags',
            field=models.ManyToManyField(related_name='jobs', to='sixerrapp.Hashtag'),
        ),
        migrations.AlterField(
            model_name='story',
            name='hashtags',
            field=models.ManyToManyField(related_name='stories', to='sixerrapp.Hashtag'),
        ),
    ]
