# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-07-05 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixerrapp', '0009_auto_20190703_0353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='requirement',
            new_name='requirements',
        ),
        migrations.AlterField(
            model_name='job',
            name='hashtags',
            field=models.ManyToManyField(to='sixerrapp.Hashtag'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='story',
            name='hashtags',
            field=models.ManyToManyField(to='sixerrapp.Hashtag'),
        ),
    ]
