# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-06-30 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixerrapp', '0010_auto_20190630_0807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='company',
            new_name='companies',
        ),
        migrations.RemoveField(
            model_name='story',
            name='category',
        ),
        migrations.RemoveField(
            model_name='story',
            name='status',
        ),
        migrations.AlterField(
            model_name='story',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
    ]
