# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-01-02 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sixerrapp', '0011_auto_20190102_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='company',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='sixerrapp.Company'),
        ),
    ]
