# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-07-26 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sixerrapp', '0011_auto_20190630_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sixerrapp.Hashtag')),
                ('hashtags', models.ManyToManyField(related_name='related_industry_hashtags', to='sixerrapp.Hashtag')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(null=True, upload_to='resumes')),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sixerrapp.Hashtag')),
                ('hashtags', models.ManyToManyField(related_name='related_sector_hashtags', to='sixerrapp.Hashtag')),
            ],
        ),
        migrations.CreateModel(
            name='SkillOrTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sixerrapp.Hashtag')),
                ('hashtags', models.ManyToManyField(related_name='related_skill_or_tool_hashtags', to='sixerrapp.Hashtag')),
                ('industries', models.ManyToManyField(to='sixerrapp.Industry')),
                ('sectors', models.ManyToManyField(to='sixerrapp.Sector')),
            ],
        ),
        migrations.RenameField(
            model_name='job',
            old_name='company',
            new_name='companies',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='description',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='company',
            name='description',
        ),
        migrations.RemoveField(
            model_name='company',
            name='time',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='resume',
        ),
        migrations.AddField(
            model_name='company',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sixerrapp.Profile'),
        ),
        migrations.AddField(
            model_name='job',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='photo',
            field=models.FileField(upload_to='stories'),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sixerrapp.Company'),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='personal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sixerrapp.Personal'),
        ),
        migrations.AddField(
            model_name='personal',
            name='companies',
            field=models.ManyToManyField(to='sixerrapp.Company'),
        ),
        migrations.AddField(
            model_name='personal',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sixerrapp.Profile'),
        ),
        migrations.AddField(
            model_name='job',
            name='hashtags',
            field=models.ManyToManyField(to='sixerrapp.Hashtag'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hashtags',
            field=models.ManyToManyField(to='sixerrapp.Hashtag'),
        ),
        migrations.AddField(
            model_name='story',
            name='hashtags',
            field=models.ManyToManyField(to='sixerrapp.Hashtag'),
        ),
    ]
