# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-08-02 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sixerrapp', '0012_auto_20190726_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='companies',
            new_name='company',
        ),
    ]
