# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-08-08 04:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sixerrapp', '0014_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='commenter',
            new_name='user',
        ),
    ]
