# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-08-08 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sixerrapp', '0015_auto_20190808_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sixerrapp.Personal'),
        ),
    ]
