# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-01-02 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixerrapp', '0002_auto_20190102_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
