# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-01-30 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixerrapp', '0005_auto_20190106_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.FileField(null=True, upload_to='resumes'),
        ),
    ]
