# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-06-29 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sixerrapp', '0009_auto_20190616_1829'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gig',
            new_name='Story',
        ),
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
